spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qa
    username: root
    password: Ltmt26118499
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
#  main:
server:
  port: 8081
#    web-application-type: none